#!/usr/bin/env ruby
# frozen_string_literal: true

APP_PATH = File.expand_path('../config/application', __dir__)

require_relative '../config/environment'

SolidusQuietLogistics::Inbound::QueuePoller.new.start do |message|
  Rails.logger.debug message.body
end
